// apps/web/src/components/ui/card.tsx
import { forwardRef, type HTMLAttributes } from "react";
import { cn } from "../../lib/utils";

export function Card({
  as: Comp = "div",
  className,
  ...props
}: HTMLAttributes<HTMLElement> & { as?: "div" | "section" | "article" }) {
  return <Comp className={cn("rounded-xl border border-ink/10 bg-white text-ink shadow-sm", className)} {...props} />;
}

export const CardHeader = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => <div ref={ref} className={cn("flex flex-col gap-1.5 p-5", className)} {...props} />
);
CardHeader.displayName = "CardHeader";

export const CardContent = forwardRef<HTMLDivElement, HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => <div ref={ref} className={cn("p-5 pt-0", className)} {...props} />
);
CardContent.displayName = "CardContent";

// apps/web/src/components/ui/Card.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { cn } from "../../lib/utils";
  let { children, class: className = "", as = "div" }: { children?: Snippet; class?: string; as?: "div" | "section" | "article" } = $props();
  const classes = $derived(cn("rounded-xl border border-border bg-card text-card-foreground shadow-xs", className));
</script>

{#if as === "section"}
  <section class={classes}>{@render children?.()}</section>
{:else if as === "article"}
  <article class={classes}>{@render children?.()}</article>
{:else}
  <div class={classes}>{@render children?.()}</div>
{/if}
